// Export all stylist components for easy importing
export { default as StylistSection } from './StylistSection';
export { default as StylistPageTitle } from './StylistPageTitle';
export { default as StylistFilterTab } from './StylistFilterTab';
export { default as StylistButton } from './StylistButton';
export { default as StylistCard } from './StylistCard';
export { default as StylistBadge } from './StylistBadge';
export { default as StylistSearchBar } from './StylistSearchBar';
export { default as ClientTypeLegend } from './ClientTypeLegend';
export { default as StylistPagination } from './StylistPagination';
